project:
    home: /Users/whee/sehat/workspace/siapkaban/be/siapkaban

layanan:
    document:
        bc:
            logo: C:\Users\ahmad\Documents\tamz\My Proj\Siapkaban\dokfolder\logo\logo.jpeg
        path: /Users/whee/sehat/workspace/siapkaban/be/file/docs
    generated:
        report:
            path: /Users/whee/sehat/workspace/siapkaban/be/file/docs
    images:
        path: /Users/whee/sehat/workspace/siapkaban/be/file/images
    jasper:
        path: ${project.home}/src/main/resources/report

server:
    port: 8089

siapkaban:
    datasource:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/siapkaban2
        password: sehatmaru
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
#        generate-ddl: true
#        hibernate:
#            ddl-auto: update
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
        jdbc-url: jdbc:postgresql://localhost:5432/siapkaban2
        url: jdbc:postgresql://localhost:5432/siapkaban2
        password: sehatmaru
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
#        generate-ddl: true
#        hibernate:
#            ddl-auto: update

    mail:
        default-encoding: UTF-8
        host: smtp.gmail.com
        username: siapkaban@gmail.com
        password: Bckaban01#
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        protocol: smtp

vaadin:
    compatibilityMode: true
    original:
        frontend:
            resources: true
    productionMode: true
